from enum import Enum

class BusyGetLastResetCode(Enum):
    UNDEFINED = 0
    POWER_ON_RESET = 1
    SOFTWARE_RESETS_THE_DIGITAL_CORE = 3
    DEEP_SLEEP_RESET_THE_DIGITAL_CORE = 5
    SDIO_MODULE_RESETS_THE_DIGITAL_CORE = 6
    MAIN_WATCH_DOG_0_RESETS_THE_DIGITAL_CORE = 7
    MAIN_WATCH_DOG_1_RESETS_THE_DIGITAL_CORE = 8
    RTC_WATCH_DOG_RESETS_THE_DIGITAL_CORE = 9
    MAIN_WATCH_DOG_RESETS_CPU = 11
    SOFTWARE_RESETS_CPU = 12
    RTC_WATCH_DOG_RESETS_CPU = 13
    CPU0_RESETS_CPU1 = 14
    RESET_WHEN_THE_VDD_VOLTAGE_IS_NOT_STABLE = 15
    RTC_WATCH_DOG_RESETS_DIGITAL_CORE_AND_RTC_MODULE = 16
