from enum import Enum

class ErrorCode(Enum):
    DEVICE_NAME_NOT_FOUND = 1001
    MANUFACTURE_NAME_NOT_FOUND = 1002
    DEVICE_ID_NOT_FOUND = 1003
    FIRMWARE_VERSION_NOT_FOUND = 1004
    LOCAL_HOST_ADDRESS_NOT_FOUND = 1005
    FREE_STORAGE_SIZE_NOT_FOUND = 1006
    TOTAL_STORAGE_SIZE_NOT_FOUND = 1007
    PICTURE_LIST_NOT_FOUND = 1008
    FILE_LIST_NOT_FOUND = 1009
